<?php
$title = 'People';
$this->headTitle($title);
?>
<h1><?= $this->escapeHtml($title); ?></h1>
<?php
$submit = $form->get('submit');
$submit->setAttribute('class', 'btn btn-primary');

$form->setAttribute('action', $this->url('people', [
    'action' => 'index',
]));
$form->prepare();

echo $this->form()->openTag($form);
?>
    <table class="table">
        <tr>
            <th>First name</th>
            <th>Last name</th>
            <th>Email Address</th>
            <th>Job Role</th>
            <th>Delete</th>
        </tr>		
    <?php 	
	foreach ($this->paginator as $person) :
		$id = $person->id;	
	?>
        <tr>			
            <td><input type="text" name="people[<?php echo $id; ?>][firstname]" value="<?php echo $person->firstname; ?>" /></td>
            <td><input type="text" name="people[<?php echo $id; ?>][lastname]" value="<?php echo $person->lastname; ?>" /></td>
            <td><input type="text" name="people[<?php echo $id; ?>][email]" value="<?php echo $person->email; ?>" /></td>
            <td>
			
			<select name="people[<?php echo $id; ?>][job_role]">
			<?php 
			foreach ($this->jobRoles as $jobRole) :
				if ($jobRole->id === $person->job_role) :
					$selected = " selected";
				else :
					$selected = "";
				endif;
			?>				
			  <option value="<?php echo $jobRole->id ?>"<?php echo $selected; ?>><?php echo $jobRole->name ?></option>
			<?php
			endforeach;
			?>			
			</select>		
			</td>					
			<td><input type="checkbox" name="people[<?php echo $id; ?>][delete]" value="1" /></td>
        </tr>
    <?php 		
	endforeach; 
	
	if ($this->allow_new) :
	?>
        <tr>
            <td><input type="text" id="people[-99][firstname]" name="people[-99][firstname]" placeholder="Add new..." /></td>
            <td><input type="text" name="people[-99][lastname]" placeholder="Add new..." /></td>
            <td><input type="text" name="people[-99][email]" placeholder="Add new..." /></td>
            <td>			
			<select name="people[-99][job_role]">
			<option value="-99">Add new...</option>
			<?php 
			foreach ($this->jobRoles as $jobRole) :
			?>				
			  <option value="<?php echo $jobRole->id ?>"><?php echo $jobRole->name ?></option>
			<?php
			endforeach;
			?>			
			</select>	
			</td>			
        </tr>
		<script>document.getElementById("people[-99][firstname]").focus();</script>
	<?php
	endif;
	?>
    </table>	
	<?= $this->formHidden($form->get('csrf')); ?>
	<input type="submit" value="Submit!" />
<?php
echo $this->form()->closeTag();