<div class="jumbotron">
    <h1>A <span class="zf-green">9xb</span> Tech-Test solution</h1>

    <p>
        Congratulations! You have successfully installed a
        <a href="https://github.com/sbrdbry/reimagined-octo-waddle/" target="_blank">9xb Tech-Test solution</a>.
        It's running on Zend Framework version <?= \Application\Module::VERSION ?>.
        It has an MVC architecture and is tested on Linux/Apache with a MySQL database.
    </p>
	<p>Select People or Job Roles at the top to perform CRUD operations and manipulate the database.</p>	

    <p><a class="btn btn-success btn-lg" href="https://github.com/sbrdbry/reimagined-octo-waddle/" target="_blank">Fork this project on GitHub &raquo;</a></p>
</div>

<div class="row">

    <div class="col-md-4">
        <div class="panel panel-default">
            <div class="panel-heading">
                <h3 class="panel-title">Development Choices</h3>
            </div>
            <div class="panel-body">
                <p>
                    Visit the documentation on GitHub to see the choices that were
                    made during development.
                    <a href="https://github.com/sbrdbry/reimagined-octo-waddle/blob/master/DELIVERABLES.md">Development Choices</a>,
                    <a href="https://github.com/sbrdbry/reimagined-octo-waddle/blob/master/DELIVERABLES.md">Time Keeping</a>,
                    <a href="https://github.com/sbrdbry/reimagined-octo-waddle/blob/master/DELIVERABLES.md">Instructions for Use</a>, and the <a href="https://github.com/sbrdbry/reimagined-octo-waddle/blob/master/DELIVERABLES.md">git bundle</a>!
                </p>

                <p><a class="btn btn-success pull-right" href="https://github.com/sbrdbry/reimagined-octo-waddle/blob/master/DELIVERABLES.md" target="_blank">Development Choices &raquo;</a></p>
            </div>
        </div>
    </div>

    <div class="col-md-4">
        <div class="panel panel-default">
            <div class="panel-heading">
                <h3 class="panel-title">How long did it take?</h3>
            </div>
            <div class="panel-body">
                <p>
                    A detailed record of each task and the time it took to complete 
                    is available <a href="https://github.com/sbrdbry/reimagined-octo-waddle/blob/master/DELIVERABLES.md">on GitHub</a>.
                </p>

                <p><a class="btn btn-success pull-right" href="https://github.com/sbrdbry/reimagined-octo-waddle/blob/master/DELIVERABLES.md" target="_blank">Time Keeping &raquo;</a></p>
            </div>
        </div>
    </div>

    <div class="col-md-4">
        <div class="panel panel-default">
            <div class="panel-heading">
                <h3 class="panel-title">VCS History</h3>
            </div>
            <div class="panel-body">
                <p>
                    As part of the deliverables you will also find the <a href="https://github.com/sbrdbry/reimagined-octo-waddle/blob/master/DELIVERABLES.md">git bundle</a>.
                    I'd love to hear any questions or feedback you may have
                    regarding this project. <a href="mailto:sbrdbry@gmail.com">sbrdbry@gmail.com</a>.
                </p>

                <p><a class="btn btn-success pull-right" href="#" target="_blank">VCS History &raquo;</a></p>
            </div>
        </div>
    </div>
</div>
