<?php
$title = 'Job Roles';
$this->headTitle($title);
?>
<h1><?= $this->escapeHtml($title); ?></h1>
<?php
$submit = $form->get('submit');
$submit->setAttribute('class', 'btn btn-primary');

$form->setAttribute('action', $this->url('jobrole', [
    'action' => 'index',
]));
$form->prepare();

echo $this->form()->openTag($form);
?>
    <table class="table">
        <tr>
            <th>Name</th>
            <th>Delete</th>
        </tr>		
    <?php 	
	foreach ($this->paginator as $job_role) : 
		$id = $job_role->id;
	?>
        <tr>			
            <td><input type="text" name="job_roles[<?php echo $id; ?>][name]" value="<?php echo $job_role->name; ?>" /></td>			
			<td><input type="checkbox" name="job_roles[<?php echo $id; ?>][delete]" value="1" /></td>
        </tr>
    <?php 		
	endforeach; 
	
	if ($this->allow_new) :
	?>
        <tr>
            <td><input type="text" id="job_roles[-99][name]" name="job_roles[-99][name]" placeholder="Add new..." /></td>
	
        </tr>
		<script>document.getElementById("job_roles[-99][name]").focus();</script>
	<?php
	endif;
	?>
    </table>	
	<?= $this->formHidden($form->get('csrf')); ?>
	<input type="submit" value="Submit!" />
<?php
echo $this->form()->closeTag();


